### ISSUE TITLE
Undefined index: value

### ISSUE THREAD

**Issue by BitQuarkApps** [atnasetreum/estafeta-API#1]
Saludos, haciendo pruebas locales con su repositorio, al momento de generar una guía nos encontramos con el error en la siguiente línea:

Estafeta.php
```php
$labelPDF = $xml_obj[0]['labelPDF']['value'];
```
LabelController.php
```php
$obj_info = Estafeta::crear_guia($request);
```

El error indica que el índice  `value` en la posición del arreglo `labelPDF` no existe.

**Comment by eduardo069** [comment]
Buenas tardes 
Como resolviste el problema?

**Comment by BitQuarkApps** [comment]
> Buenas tardes
> Como resolviste el problema?

Buenas tardes, sucede que cuando el XML es erróneo o nulo, el índice 

```php 
['value']
```

no existe, puede ser que tus credenciales de acceso a la API sean incorrectas o que estafeta no te ha dado el acceso al modo *live*.


O bien podrías poner las líneas de código en un *try catch* para evitar que el sitio se caiga cuando se de la excepción.
